### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by luciobortoletto** [luciobortoletto/Mc-Better-Vanilla#5]
- [ ] Create GitHub repository
- [ ] Add the first mod
- [ ] Alpha status
- [ ] Add the basic mods
- [ ] Made the modpack playable
- [ ] Add some performance mods
- [ ] Update to 1.17.* (currently not updated to 1.17.* due to some mods not being updated)
- [ ] Beta status
- [ ] Fix almost all issues
- [ ] Publish on CurseForge
- [ ] R. C. status
- [ ] Fix all issues reported
- [ ] Release!!!
